<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product')->delete();
        
        \DB::table('product')->insert(array (
            0 => 
            array (
                'product_id' => 1,
                'name' => 'Uniqlo Trousers',
                'price' => 307,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'user_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Uniqlo Trousers.png',
                'product_condition' => 'barely used',
                'brand' => 'Uniqlo',
                'material' => 'cotton spandex',
                'color' => 'khaki',
                'size_fit' => 'large, loose fit',
                'notes' => 'Slight discoloration on the waistband, small hole inside the pocket.',
            ),
            1 => 
            array (
                'product_id' => 2,
                'name' => 'H&M Blazer',
                'price' => 879,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'user_id' => 0,
                'availability' => 'available',
                'product_photo' => 'H&M Blazer.png',
                'product_condition' => 'like new',
                'brand' => 'H&M',
                'material' => 'polyester',
                'color' => 'black',
                'size_fit' => 'medium, formal fit',
                'notes' => 'Missing a button on the front, minor thread pulls on the left sleeve.',
            ),
            2 => 
            array (
                'product_id' => 3,
                'name' => 'Old Navy Shirt',
                'price' => 647,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'user_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Old Navy Shirt.png',
                'product_condition' => 'used',
                'brand' => 'Old Navy',
                'material' => 'cotton',
                'color' => 'blue',
                'size_fit' => 'small, casual fit',
                'notes' => 'Faded color around the collar, light stain near the hem.',
            ),
            3 => 
            array (
                'product_id' => 4,
                'name' => 'Zara Skirt',
                'price' => 449,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'user_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Zara Skirt.png',
                'product_condition' => 'gently used',
                'brand' => 'Zara',
                'material' => 'polyester blend',
                'color' => 'red',
                'size_fit' => 'medium, A-line',
                'notes' => 'Zipper occasionally sticks, small tear in the lining.',
            ),
            4 => 
            array (
                'product_id' => 5,
                'name' => 'Mango Dress',
                'price' => 665,
                'category' => 'Clothes',
                'nego_status' => 'non-negotiable',
                'seller_id' => 0,
                'user_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Mango Dress.png',
                'product_condition' => 'worn once',
                'brand' => 'Mango',
                'material' => 'silk',
                'color' => 'navy',
                'size_fit' => 'small, flowy',
                'notes' => 'Minor pilling on the fabric, one loose seam near the zipper.',
            ),
            5 => 
            array (
                'product_id' => 6,
                'name' => 'Topshop Jeans',
                'price' => 154,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'user_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Topshop Jeans.png',
                'product_condition' => 'well-worn',
                'brand' => 'Topshop',
                'material' => 'denim',
                'color' => 'light blue',
                'size_fit' => 'size 28, skinny fit',
                'notes' => 'Slight fraying on the hems, faded knee areas.',
            ),
            6 => 
            array (
                'product_id' => 7,
                'name' => 'Gap Hoodie',
                'price' => 307,
                'category' => 'Clothes',
                'nego_status' => 'non-negotiable',
                'seller_id' => 0,
                'user_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Gap Hoodie.png',
                'product_condition' => 'used',
                'brand' => 'Gap',
                'material' => 'fleece',
                'color' => 'grey',
                'size_fit' => 'large, oversized',
                'notes' => 'Drawstring missing, light fabric wear from regular use.',
            ),
            7 => 
            array (
                'product_id' => 8,
                'name' => 'Forever 21 Top',
                'price' => 763,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'user_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Forever 21 Top.png',
                'product_condition' => 'like new',
                'brand' => 'Forever 21',
                'material' => 'cotton',
                'color' => 'white',
                'size_fit' => 'medium, cropped',
                'notes' => 'Small ink stain on the back, slight stretching at the neckline.',
            ),
            8 => 
            array (
                'product_id' => 9,
                'name' => 'Ralph Lauren Polo',
                'price' => 979,
                'category' => 'Clothes',
                'nego_status' => 'non-negotiable',
                'seller_id' => 0,
                'user_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Ralph Lauren Polo.png',
                'product_condition' => 'vintage',
                'brand' => 'Ralph Lauren',
                'material' => 'cotton',
                'color' => 'green',
                'size_fit' => 'large, classic fit',
                'notes' => 'Color slightly faded from washing, tiny hole near the logo.',
            ),
            9 => 
            array (
                'product_id' => 10,
                'name' => 'Levi\'s Shorts',
                'price' => 899,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'user_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Levi_s Shorts.png',
                'product_condition' => 'gently used',
                'brand' => 'Levi\'s',
                'material' => 'denim',
                'color' => 'black',
                'size_fit' => '30 waist, regular fit',
                'notes' => 'Distressed look, small paint splatters on the back pocket.',
            ),
            10 => 
            array (
                'product_id' => 11,
                'name' => 'Calvin Klein T-Shirt',
                'price' => 359,
                'category' => 'Clothes',
                'nego_status' => 'non-negotiable',
                'seller_id' => 0,
                'user_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Calvin Klein T-Shirt.png',
                'product_condition' => 'lightly used',
                'brand' => 'Calvin Klein',
                'material' => 'cotton',
                'color' => 'white',
                'size_fit' => 'medium, slim fit',
                'notes' => 'Logo slightly cracked, fabric slightly thin from wear.',
            ),
            11 => 
            array (
                'product_id' => 12,
                'name' => 'Guess Jacket',
                'price' => 125,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'user_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Guess Jacket.png',
                'product_condition' => 'barely used',
                'brand' => 'Guess',
                'material' => 'leather',
                'color' => 'brown',
                'size_fit' => 'medium, biker style',
                'notes' => 'Wear on the cuffs, one inner pocket seam coming undone.',
            ),
            12 => 
            array (
                'product_id' => 13,
                'name' => 'Nike Sweatpants',
                'price' => 371,
                'category' => 'Clothes',
                'nego_status' => 'non-negotiable',
                'seller_id' => 1,
                'user_id' => 1,
                'availability' => 'available',
                'product_photo' => 'Nike Sweatpants.png',
                'product_condition' => 'used',
                'brand' => 'Nike',
                'material' => 'polyester',
                'color' => 'black',
                'size_fit' => 'large, relaxed fit',
                'notes' => 'Drawstring frayed, light pilling on the inner thigh area.',
            ),
            13 => 
            array (
                'product_id' => 14,
                'name' => 'Adidas Track Jacket',
                'price' => 873,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 1,
                'user_id' => 1,
                'availability' => 'available',
                'product_photo' => 'Adidas Track Jacket.png',
                'product_condition' => 'like new',
                'brand' => 'Adidas',
                'material' => 'polyester',
                'color' => 'navy',
                'size_fit' => 'small, athletic fit',
                'notes' => 'Slight discoloration under the arms, logo starting to peel off.',
            ),
            14 => 
            array (
                'product_id' => 15,
                'name' => 'Lacoste Sweater',
                'price' => 736,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 1,
                'user_id' => 1,
                'availability' => 'available',
                'product_photo' => 'Lacoste Sweater.png',
                'product_condition' => 'well-worn',
                'brand' => 'Lacoste',
                'material' => 'wool',
                'color' => 'cream',
                'size_fit' => 'medium, snug fit',
                'notes' => 'Minor shrinkage, small moth hole near the waistband.',
            ),
            15 => 
            array (
                'product_id' => 16,
                'name' => 'ASOS Maxi Dress',
                'price' => 974,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 1,
                'user_id' => 1,
                'availability' => 'available',
                'product_photo' => 'ASOS Maxi Dress.png',
                'product_condition' => 'used',
                'brand' => 'ASOS',
                'material' => 'viscose',
                'color' => 'floral',
                'size_fit' => 'small, empire waist',
                'notes' => 'Hem slightly uneven, faint makeup marks on the collar.',
            ),
            16 => 
            array (
                'product_id' => 17,
                'name' => 'Tommy Hilfiger Denim Jacket',
                'price' => 331,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 1,
                'user_id' => 1,
                'availability' => 'available',
                'product_photo' => 'Tommy Hilfiger Denim Jacket.png',
                'product_condition' => 'gently used',
                'brand' => 'Tommy Hilfiger',
                'material' => 'denim',
                'color' => 'blue',
                'size_fit' => 'large, classic fit',
                'notes' => 'Slight rust on buttons, denim color slightly washed out.',
            ),
            17 => 
            array (
                'product_id' => 18,
                'name' => 'Puma Sports Tee',
                'price' => 676,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 1,
                'user_id' => 1,
                'availability' => 'available',
                'product_photo' => 'Puma Sports Tee.png',
                'product_condition' => 'lightly used',
                'brand' => 'Puma',
                'material' => 'polyester',
                'color' => 'red',
                'size_fit' => 'medium, regular fit',
                'notes' => 'Print faded from washing, fabric shows signs of stretching.',
            ),
            18 => 
            array (
                'product_id' => 19,
                'name' => 'American Eagle Outfitters Shorts',
                'price' => 478,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 1,
                'user_id' => 1,
                'availability' => 'available',
                'product_photo' => 'American Eagle Outfitters Shorts.png',
                'product_condition' => 'used',
                'brand' => 'American Eagle',
                'material' => 'cotton',
                'color' => 'khaki',
                'size_fit' => '32 waist, regular fit',
                'notes' => 'Distressed edges, slight color fade on the seams.',
            ),
            19 => 
            array (
                'product_id' => 20,
                'name' => 'Burberry Trench Coat',
                'price' => 607,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 1,
                'user_id' => 1,
                'availability' => 'available',
                'product_photo' => 'Burberry Trench Coat.png',
                'product_condition' => 'vintage',
                'brand' => 'Burberry',
                'material' => 'cotton gabardine',
                'color' => 'beige',
                'size_fit' => 'medium, tailored fit',
                'notes' => 'Slight water stain on the lower back.',
            ),
            20 => 
            array (
                'product_id' => 21,
                'name' => 'Adidas Running Shoes',
                'price' => 540,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 1,
                'user_id' => 1,
                'availability' => 'available',
                'product_photo' => 'Adidas Running Shoes.png',
                'product_condition' => 'well-worn',
                'brand' => 'Adidas',
                'material' => 'synthetic',
                'color' => 'black',
                'size_fit' => 'size 10, snug fit',
                'notes' => 'Sole slightly worn, insole shows signs of wear.',
            ),
            21 => 
            array (
                'product_id' => 22,
                'name' => 'Nike Air Max',
                'price' => 433,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 1,
                'user_id' => 1,
                'availability' => 'available',
                'product_photo' => 'Nike Air Max.png',
                'product_condition' => 'moderately used',
                'brand' => 'Nike',
                'material' => 'mesh',
                'color' => 'grey',
                'size_fit' => 'size 9, cushioned sole',
                'notes' => 'Minor scuff on the toe box, laces slightly frayed.',
            ),
            22 => 
            array (
                'product_id' => 23,
                'name' => 'Converse All-Stars',
                'price' => 599,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 1,
                'user_id' => 1,
                'availability' => 'available',
                'product_photo' => 'Converse All-Stars.png',
                'product_condition' => 'lightly used',
                'brand' => 'Converse',
                'material' => 'canvas',
                'color' => 'red',
                'size_fit' => 'size 8, standard fit',
                'notes' => 'Canvas faded, small tear near the ankle.',
            ),
            23 => 
            array (
                'product_id' => 24,
                'name' => 'Dr. Martens Boots',
                'price' => 521,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 1,
                'user_id' => 1,
                'availability' => 'available',
                'product_photo' => 'Dr. Martens Boots.png',
                'product_condition' => 'vintage',
                'brand' => 'Dr. Martens',
                'material' => 'leather',
                'color' => 'black',
                'size_fit' => 'size 7, tight fit',
                'notes' => 'Leather creased at ankles, slight scuffing on the toes.',
            ),
            24 => 
            array (
                'product_id' => 25,
                'name' => 'Vans Skate Shoes',
                'price' => 569,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 2,
                'user_id' => 2,
                'availability' => 'available',
                'product_photo' => 'Vans Skate Shoes.png',
                'product_condition' => 'used',
                'brand' => 'Vans',
                'material' => 'canvas',
                'color' => 'checkered',
                'size_fit' => 'size 11, comfortable fit',
                'notes' => 'Faded pattern, slight detachment of the sole at the heel.',
            ),
            25 => 
            array (
                'product_id' => 26,
                'name' => 'Birkenstock Sandals',
                'price' => 595,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 2,
                'user_id' => 2,
                'availability' => 'available',
                'product_photo' => 'Birkenstock Sandals.png',
                'product_condition' => 'well-worn',
                'brand' => 'Birkenstock',
                'material' => 'cork and leather',
                'color' => 'brown',
                'size_fit' => 'size 6, wide fit',
                'notes' => 'Footbed shows imprint, buckle slightly tarnished.',
            ),
            26 => 
            array (
                'product_id' => 27,
                'name' => 'Steve Madden Heels',
                'price' => 170,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 2,
                'user_id' => 2,
                'availability' => 'available',
                'product_photo' => 'Steve Madden Heels.png',
                'product_condition' => 'lightly used',
                'brand' => 'Steve Madden',
                'material' => 'suede',
                'color' => 'black',
                'size_fit' => 'size 7, high heel',
                'notes' => 'Heel tips worn, slight scuffs on the suede.',
            ),
            27 => 
            array (
                'product_id' => 28,
                'name' => 'Clarks Desert Boots',
                'price' => 456,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 2,
                'user_id' => 2,
                'availability' => 'available',
                'product_photo' => 'Clarks Desert Boots.png',
                'product_condition' => 'gently used',
                'brand' => 'Clarks',
                'material' => 'suede',
                'color' => 'brown',
                'size_fit' => 'size 9, classic fit',
                'notes' => 'Leather creased, soles show moderate wear.',
            ),
            28 => 
            array (
                'product_id' => 29,
                'name' => 'Reebok Trainers',
                'price' => 945,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 2,
                'user_id' => 2,
                'availability' => 'available',
                'product_photo' => 'Reebok Trainers.png',
                'product_condition' => 'used',
                'brand' => 'Reebok',
                'material' => 'mesh',
                'color' => 'blue',
                'size_fit' => 'size 10, athletic fit',
                'notes' => 'Fabric slightly loose on one side, insole slightly worn.',
            ),
            29 => 
            array (
                'product_id' => 30,
                'name' => 'Jimmy Choo High Heels',
                'price' => 478,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 2,
                'user_id' => 2,
                'availability' => 'available',
                'product_photo' => 'Jimmy Choo High Heels.png',
                'product_condition' => 'barely used',
                'brand' => 'Jimmy Choo',
                'material' => 'leather',
                'color' => 'grey',
                'size_fit' => 'size 8, elegant fit',
                'notes' => 'Minor scuffs on the heel, wear on sole tips.',
            ),
            30 => 
            array (
                'product_id' => 31,
                'name' => 'New Balance Sneakers',
                'price' => 696,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 2,
                'user_id' => 2,
                'availability' => 'available',
                'product_photo' => 'New Balance Sneakers.png',
                'product_condition' => 'well-worn',
                'brand' => 'New Balance',
                'material' => 'suede and mesh',
                'color' => 'grey',
                'size_fit' => 'size 11, comfortable fit',
                'notes' => 'Slight discoloration on the mesh, laces replaced.',
            ),
            31 => 
            array (
                'product_id' => 32,
                'name' => 'Timberland Boots',
                'price' => 698,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 2,
                'user_id' => 2,
                'availability' => 'available',
                'product_photo' => 'Timberland Boots.png',
                'product_condition' => 'moderately used',
                'brand' => 'Timberland',
                'material' => 'leather',
                'color' => 'wheat',
                'size_fit' => 'size 12, rugged fit',
                'notes' => 'Leather slightly scuffed, stitching loose on the right boot.',
            ),
            32 => 
            array (
                'product_id' => 33,
                'name' => 'Gucci Loafers',
                'price' => 886,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 2,
                'user_id' => 2,
                'availability' => 'available',
                'product_photo' => 'Gucci Loafers.png',
                'product_condition' => 'like new',
                'brand' => 'Gucci',
                'material' => 'leather',
                'color' => 'black',
                'size_fit' => 'size 8, luxury fit',
                'notes' => 'Creases on the top, heel shows wear.',
            ),
            33 => 
            array (
                'product_id' => 34,
                'name' => 'Crocs Sandals',
                'price' => 828,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 2,
                'user_id' => 2,
                'availability' => 'available',
                'product_photo' => 'Crocs Sandals.png',
                'product_condition' => 'used',
                'brand' => 'Crocs',
                'material' => 'rubber',
                'color' => 'navy',
                'size_fit' => 'size 7, relaxed fit',
                'notes' => 'Color faded from sunlight exposure, strap slightly stretched.',
            ),
            34 => 
            array (
                'product_id' => 35,
                'name' => 'Skechers Walking Shoes',
                'price' => 757,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 2,
                'user_id' => 2,
                'availability' => 'available',
                'product_photo' => 'Skechers Walking Shoes.png',
                'product_condition' => 'lightly used',
                'brand' => 'Skechers',
                'material' => 'mesh',
                'color' => 'black',
                'size_fit' => 'size 9, cushioned fit',
                'notes' => 'Insoles compressed, slight wear on the tread.',
            ),
            35 => 
            array (
                'product_id' => 36,
                'name' => 'Puma Running Shoes',
                'price' => 404,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 2,
                'user_id' => 2,
                'availability' => 'available',
                'product_photo' => 'Puma Running Shoes.png',
                'product_condition' => 'gently used',
                'brand' => 'Puma',
                'material' => 'synthetic',
                'color' => 'white',
                'size_fit' => 'size 10, sporty fit',
                'notes' => 'Mesh slightly torn near the toe, sole worn down.',
            ),
            36 => 
            array (
                'product_id' => 37,
                'name' => 'Balenciaga Sneakers',
                'price' => 610,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 3,
                'user_id' => 3,
                'availability' => 'available',
                'product_photo' => 'Balenciaga Sneakers.png',
                'product_condition' => 'like new',
                'brand' => 'Balenciaga',
                'material' => 'leather',
                'color' => 'white',
                'size_fit' => 'size 11, oversized fit',
                'notes' => 'Leather creased at the toe, minor scuff marks.',
            ),
            37 => 
            array (
                'product_id' => 38,
                'name' => 'Yeezy Boost 350',
                'price' => 823,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 3,
                'user_id' => 3,
                'availability' => 'available',
                'product_photo' => 'Yeezy Boost 350.png',
                'product_condition' => 'worn once',
                'brand' => 'Yeezy',
                'material' => 'knit',
                'color' => 'black',
                'size_fit' => 'size 9, snug fit',
                'notes' => 'Slight discoloration on the knit upper, sole slightly dirty.',
            ),
            38 => 
            array (
                'product_id' => 39,
                'name' => 'Under Armour Sports Shoes',
                'price' => 849,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 3,
                'user_id' => 3,
                'availability' => 'available',
                'product_photo' => 'Under Armour Sports Shoes.png',
                'product_condition' => 'moderately used',
                'brand' => 'Under Armour',
                'material' => 'synthetic',
                'color' => 'red',
                'size_fit' => 'size 8, athletic fit',
                'notes' => 'Laces slightly frayed, minor wear on the inner lining.',
            ),
            39 => 
            array (
                'product_id' => 40,
                'name' => 'Salvatore Ferragamo Dress Shoes',
                'price' => 658,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 3,
                'user_id' => 3,
                'availability' => 'available',
                'product_photo' => 'Salvatore Ferragamo Dress Shoes.png',
                'product_condition' => 'vintage',
                'brand' => 'Salvatore Ferragamo',
                'material' => 'leather',
                'color' => 'black',
                'size_fit' => 'size 10, elegant fit',
                'notes' => 'Leather scuffed at toes, insole slightly worn.',
            ),
            40 => 
            array (
                'product_id' => 41,
                'name' => 'Michael Kors Handbag',
                'price' => 723,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 3,
                'user_id' => 3,
                'availability' => 'available',
                'product_photo' => 'Michael Kors Handbag.png',
                'product_condition' => 'like new',
                'brand' => 'Michael Kors',
                'material' => 'leather',
                'color' => 'tan',
                'size_fit' => 'medium-sized, spacious interior',
                'notes' => 'Minor scratches on hardware, interior lining stained.',
            ),
            41 => 
            array (
                'product_id' => 42,
                'name' => 'Coach Shoulder Bag',
                'price' => 473,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 3,
                'user_id' => 3,
                'availability' => 'available',
                'product_photo' => 'Coach Shoulder Bag.png',
                'product_condition' => 'barely used',
                'brand' => 'Coach',
                'material' => 'canvas and leather',
                'color' => 'brown',
                'size_fit' => 'small, compact design',
                'notes' => 'Leather slightly faded, strap shows signs of wear.',
            ),
            42 => 
            array (
                'product_id' => 43,
                'name' => 'Kate Spade Clutch',
                'price' => 211,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 3,
                'user_id' => 3,
                'availability' => 'available',
                'product_photo' => 'Kate Spade Clutch.png',
                'product_condition' => 'like new',
                'brand' => 'Kate Spade',
                'material' => 'satin',
                'color' => 'black',
                'size_fit' => 'one size, elegant look',
                'notes' => 'Minor scratch on the clasp, small pen mark inside.',
            ),
            43 => 
            array (
                'product_id' => 44,
                'name' => 'Longchamp Tote Bag',
                'price' => 156,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 3,
                'user_id' => 3,
                'availability' => 'available',
                'product_photo' => 'Longchamp Tote Bag.png',
                'product_condition' => 'gently used',
                'brand' => 'Longchamp',
                'material' => 'nylon',
                'color' => 'pink',
                'size_fit' => 'large, foldable',
                'notes' => 'Corners worn, small ink stain on the interior.',
            ),
            44 => 
            array (
                'product_id' => 45,
                'name' => 'Prada Crossbody Bag',
                'price' => 538,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 3,
                'user_id' => 3,
                'availability' => 'available',
                'product_photo' => 'Prada Crossbody Bag.png',
                'product_condition' => 'like new',
                'brand' => 'Prada',
                'material' => 'Saffiano leather',
                'color' => 'red',
                'size_fit' => 'medium, adjustable strap',
                'notes' => 'Slight wear on the strap, small scuff on the bottom corner.',
            ),
            45 => 
            array (
                'product_id' => 46,
                'name' => 'Fossil Satchel',
                'price' => 389,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 3,
                'user_id' => 3,
                'availability' => 'available',
                'product_photo' => 'Fossil Satchel.png',
                'product_condition' => 'barely used',
                'brand' => 'Fossil',
                'material' => 'leather',
                'color' => 'grey',
                'size_fit' => 'medium, multiple pockets',
                'notes' => 'Zipper sticks occasionally, slight discoloration on the back.',
            ),
            46 => 
            array (
                'product_id' => 47,
                'name' => 'Louis Vuitton Speedy',
                'price' => 957,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 3,
                'user_id' => 3,
                'availability' => 'available',
                'product_photo' => 'Louis Vuitton Speedy.png',
                'product_condition' => 'vintage',
                'brand' => 'Louis Vuitton',
                'material' => 'canvas and leather',
                'color' => 'brown',
                'size_fit' => 'small, iconic design',
                'notes' => 'Handles darkened from use, interior pocket peeling.',
            ),
            47 => 
            array (
                'product_id' => 48,
                'name' => 'Gucci Marmont',
                'price' => 118,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 3,
                'user_id' => 3,
                'availability' => 'available',
                'product_photo' => 'Gucci Marmont.png',
                'product_condition' => 'well-worn',
                'brand' => 'Gucci',
                'material' => 'leather',
                'color' => 'black',
                'size_fit' => 'medium, luxury style',
                'notes' => 'Minor scratch on the front flap, hardware slightly tarnished.',
            ),
            48 => 
            array (
                'product_id' => 49,
                'name' => 'Hermes Birkin',
                'price' => 714,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 5,
                'user_id' => 5,
                'availability' => 'available',
                'product_photo' => 'Hermes Birkin.png',
                'product_condition' => 'lightly used',
                'brand' => 'Hermes',
                'material' => 'leather',
                'color' => 'beige',
                'size_fit' => 'large, exclusive design',
                'notes' => 'Slight wear on the corners, lock and key missing.',
            ),
            49 => 
            array (
                'product_id' => 50,
                'name' => 'Chanel Flap Bag',
                'price' => 296,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 5,
                'user_id' => 5,
                'availability' => 'available',
                'product_photo' => 'Chanel Flap Bag.png',
                'product_condition' => 'vintage',
                'brand' => 'Chanel',
                'material' => 'leather',
                'color' => 'navy',
                'size_fit' => 'medium, classic style',
                'notes' => 'Chain strap shows wear, leather slightly stretched on the flap.',
            ),
            50 => 
            array (
                'product_id' => 51,
                'name' => 'Marc Jacobs Backpack',
                'price' => 699,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 5,
                'user_id' => 5,
                'availability' => 'available',
                'product_photo' => 'Marc Jacobs Backpack.png',
                'product_condition' => 'used',
                'brand' => 'Marc Jacobs',
                'material' => 'nylon',
                'color' => 'black',
                'size_fit' => 'large, casual look',
                'notes' => 'Zipper tab missing, fabric slightly faded.',
            ),
            51 => 
            array (
                'product_id' => 52,
                'name' => 'YSL Clutch',
                'price' => 873,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 5,
                'user_id' => 5,
                'availability' => 'available',
                'product_photo' => 'YSL Clutch.png',
                'product_condition' => 'like new',
                'brand' => 'Yves Saint Laurent',
                'material' => 'leather',
                'color' => 'red',
                'size_fit' => 'medium, chic style',
                'notes' => 'Minor marks on the leather, magnetic closure slightly loose.',
            ),
            52 => 
            array (
                'product_id' => 53,
                'name' => 'Givenchy Antigona',
                'price' => 917,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 5,
                'user_id' => 5,
                'availability' => 'available',
                'product_photo' => 'Givenchy Antigona.png',
                'product_condition' => 'gently used',
                'brand' => 'Givenchy',
                'material' => 'leather',
                'color' => 'grey',
                'size_fit' => 'medium, structured design',
                'notes' => 'Small stain inside, hardware slightly scratched.',
            ),
            53 => 
            array (
                'product_id' => 54,
                'name' => 'Alexander Wang Bucket Bag',
                'price' => 367,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 5,
                'user_id' => 5,
                'availability' => 'available',
                'product_photo' => 'Alexander Wang Bucket Bag.png',
                'product_condition' => 'barely used',
                'brand' => 'Alexander Wang',
                'material' => 'leather',
                'color' => 'black',
                'size_fit' => 'small, modern style',
                'notes' => 'Leather creased, interior fabric shows wear.',
            ),
            54 => 
            array (
                'product_id' => 55,
                'name' => 'Tory Burch Tote',
                'price' => 174,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 5,
                'user_id' => 5,
                'availability' => 'available',
                'product_photo' => 'Tory Burch Tote.png',
                'product_condition' => 'used',
                'brand' => 'Tory Burch',
                'material' => 'canvas',
                'color' => 'navy',
                'size_fit' => 'large, versatile design',
                'notes' => 'Straps slightly frayed, small makeup stain inside.',
            ),
            55 => 
            array (
                'product_id' => 56,
                'name' => 'Chloe Drew Bag',
                'price' => 854,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 5,
                'user_id' => 5,
                'availability' => 'available',
                'product_photo' => 'Chloe Drew Bag.png',
                'product_condition' => 'lightly used',
                'brand' => 'Chloe',
                'material' => 'leather',
                'color' => 'tan',
                'size_fit' => 'small, elegant look',
                'notes' => 'Slight scratch on the front, clasp shows wear.',
            ),
            56 => 
            array (
                'product_id' => 57,
                'name' => 'Burberry Crossbody',
                'price' => 558,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 5,
                'user_id' => 5,
                'availability' => 'available',
                'product_photo' => 'Burberry Crossbody.png',
                'product_condition' => 'vintage',
                'brand' => 'Burberry',
                'material' => 'check canvas',
                'color' => 'beige',
                'size_fit' => 'medium, classic design',
                'notes' => 'Buckle slightly tarnished, minor wear on the corners.',
            ),
            57 => 
            array (
                'product_id' => 58,
                'name' => 'Valentino Shoulder Bag',
                'price' => 582,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 5,
                'user_id' => 5,
                'availability' => 'available',
                'product_photo' => 'Valentino Shoulder Bag.png',
                'product_condition' => 'like new',
                'brand' => 'Valentino',
                'material' => 'leather',
                'color' => 'black',
                'size_fit' => 'medium, rockstud details',
                'notes' => 'Studs slightly tarnished, leather creased on the back.',
            ),
            58 => 
            array (
                'product_id' => 59,
                'name' => 'Miu Miu Satchel',
                'price' => 280,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 5,
                'user_id' => 5,
                'availability' => 'available',
                'product_photo' => 'Miu Miu Satchel.png',
                'product_condition' => 'gently used',
                'brand' => 'Miu Miu',
                'material' => 'leather',
                'color' => 'pink',
                'size_fit' => 'small, feminine style',
                'notes' => 'Minor wear on the handle, small pen marks on the lining.',
            ),
            59 => 
            array (
                'product_id' => 60,
                'name' => 'Dolce & Gabbana Clutch',
                'price' => 504,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 5,
                'user_id' => 5,
                'availability' => 'available',
                'product_photo' => 'Dolce & Gabbana Clutch.png',
                'product_condition' => 'barely used',
                'brand' => 'Dolce & Gabbana',
                'material' => 'leather',
                'color' => 'gold',
                'size_fit' => 'one size, glamorous look',
                'notes' => 'Fabric slightly pulled at the corners, clasp slightly loose.',
            ),
        ));
        
        
    }
}