<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product')->delete();
        
        \DB::table('product')->insert(array (
            0 => 
            array (
                'product_id' => 1,
                'name' => 'Uniqlo Trousers',
                'price' => 307,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Uniqlo Trousers.png',
                'product_condition' => 'barely used',
                'brand' => 'Uniqlo',
                'meterial' => 'cotton spandex',
                'color' => 'khaki',
                'size_fit' => 'large, loose fit',
                'notes' => 'Uniqlo Trousers-barely used Uniqlo cotton spandex khaki large, loose fit Slight discoloration on the',
            ),
            1 => 
            array (
                'product_id' => 2,
                'name' => 'H&M Blazer',
                'price' => 879,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'H&M Blazer.png',
                'product_condition' => 'like new',
                'brand' => 'H&M',
                'meterial' => 'polyester',
                'color' => 'black',
                'size_fit' => 'medium, formal fit',
                'notes' => 'H&M Blazer-like new H&M polyester black medium, formal fit Missing a button on the front, minor thre',
            ),
            2 => 
            array (
                'product_id' => 3,
                'name' => 'Old Navy Shirt',
                'price' => 647,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Old Navy Shirt.png',
                'product_condition' => 'used',
                'brand' => 'Old Navy',
                'meterial' => 'cotton',
                'color' => 'blue',
                'size_fit' => 'small, casual fit',
                'notes' => 'Old Navy Shirt-used Old Navy cotton blue small, casual fit Faded color around the collar, light stai',
            ),
            3 => 
            array (
                'product_id' => 4,
                'name' => 'Zara Skirt',
                'price' => 449,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Zara Skirt.png',
                'product_condition' => 'gently used',
                'brand' => 'Zara',
                'meterial' => 'polyester blend',
                'color' => 'red',
                'size_fit' => 'medium, A-line',
                'notes' => 'Zara Skirt-gently used Zara polyester blend red medium, A-line Zipper occasionally sticks, small tea',
            ),
            4 => 
            array (
                'product_id' => 5,
                'name' => 'Mango Dress',
                'price' => 665,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Mango Dress.png',
                'product_condition' => 'worn once',
                'brand' => 'Mango',
                'meterial' => 'silk',
                'color' => 'navy',
                'size_fit' => 'small, flowy',
                'notes' => 'Mango Dress-worn once Mango silk navy small, flowy Minor pilling on the fabric, one loose seam near ',
            ),
            5 => 
            array (
                'product_id' => 6,
                'name' => 'Topshop Jeans',
                'price' => 154,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Topshop Jeans.png',
                'product_condition' => 'well-worn',
                'brand' => 'Topshop',
                'meterial' => 'denim',
                'color' => 'light blue',
                'size_fit' => 'size 28, skinny fit',
                'notes' => 'Topshop Jeans-well-worn Topshop denim light blue size 28, skinny fit Slight fraying on the hems, fad',
            ),
            6 => 
            array (
                'product_id' => 7,
                'name' => 'Gap Hoodie',
                'price' => 307,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Gap Hoodie.png',
                'product_condition' => 'used',
                'brand' => 'Gap',
                'meterial' => 'fleece',
                'color' => 'grey',
                'size_fit' => 'large, oversized',
                'notes' => 'Gap Hoodie-used Gap fleece grey large, oversized Drawstring missing, light fabric wear from regular ',
            ),
            7 => 
            array (
                'product_id' => 8,
                'name' => 'Forever 21 Top',
                'price' => 763,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Forever 21 Top.png',
                'product_condition' => 'like new',
                'brand' => 'Forever 21',
                'meterial' => 'cotton',
                'color' => 'white',
                'size_fit' => 'medium, cropped',
                'notes' => 'Forever 21 Top-like new Forever 21 cotton white medium, cropped Small ink stain on the back, slight ',
            ),
            8 => 
            array (
                'product_id' => 9,
                'name' => 'Ralph Lauren Polo',
                'price' => 979,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Ralph Lauren Polo.png',
                'product_condition' => 'vintage',
                'brand' => 'Ralph Lauren',
                'meterial' => 'cotton',
                'color' => 'green',
                'size_fit' => 'large, classic fit',
                'notes' => 'Color slightly faded from washing, tiny hole near the logo.',
            ),
            9 => 
            array (
                'product_id' => 10,
                'name' => 'Levi\'s Shorts',
                'price' => 899,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Levi\'s Shorts.png',
                'product_condition' => 'gently used',
                'brand' => 'Levi\'s',
                'meterial' => 'denim',
                'color' => 'black',
                'size_fit' => '',
                'notes' => 'Distressed look, small paint splatters on the back pocket.',
            ),
            10 => 
            array (
                'product_id' => 11,
                'name' => 'Calvin Klein T-Shirt',
                'price' => 359,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Calvin Klein T-Shirt.png',
                'product_condition' => 'lightly used',
                'brand' => 'Calvin Klein',
                'meterial' => 'cotton',
                'color' => 'white',
                'size_fit' => 'medium, slim fit',
                'notes' => 'Calvin Klein T-Shirt-lightly used Calvin Klein cotton white medium, slim fit Logo slightly cracked, ',
            ),
            11 => 
            array (
                'product_id' => 12,
                'name' => 'Guess Jacket',
                'price' => 125,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Guess Jacket.png',
                'product_condition' => 'barely used',
                'brand' => 'Guess',
                'meterial' => 'leather',
                'color' => 'brown',
                'size_fit' => 'medium, biker style',
                'notes' => 'Guess Jacket-barely used Guess leather brown medium, biker style Wear on the cuffs, one inner pocket',
            ),
            12 => 
            array (
                'product_id' => 13,
                'name' => 'Nike Sweatpants',
                'price' => 371,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Nike Sweatpants.png',
                'product_condition' => 'used',
                'brand' => 'Nike',
                'meterial' => 'polyester',
                'color' => 'black',
                'size_fit' => 'large, relaxed fit',
                'notes' => 'Nike Sweatpants-used Nike polyester black large, relaxed fit Drawstring frayed, light pilling on the',
            ),
            13 => 
            array (
                'product_id' => 14,
                'name' => 'Adidas Track Jacket',
                'price' => 873,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Adidas Track Jacket.png',
                'product_condition' => 'like new',
                'brand' => 'Adidas',
                'meterial' => 'polyester',
                'color' => 'navy',
                'size_fit' => 'small, athletic fit',
                'notes' => 'Adidas Track Jacket-like new Adidas polyester navy small, athletic fit Slight discoloration under th',
            ),
            14 => 
            array (
                'product_id' => 15,
                'name' => 'Lacoste Sweater',
                'price' => 736,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Lacoste Sweater.png',
                'product_condition' => 'well-worn',
                'brand' => 'Lacoste',
                'meterial' => 'wool',
                'color' => 'cream',
                'size_fit' => 'medium, snug fit',
                'notes' => 'Lacoste Sweater-well-worn Lacoste wool cream medium, snug fit Minor shrinkage, small moth hole near ',
            ),
            15 => 
            array (
                'product_id' => 16,
                'name' => 'ASOS Maxi Dress',
                'price' => 974,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'ASOS Maxi Dress.png',
                'product_condition' => 'used',
                'brand' => 'ASOS',
                'meterial' => 'viscose',
                'color' => 'floral',
                'size_fit' => 'small, empire waist',
                'notes' => 'ASOS Maxi Dress-used ASOS viscose floral small, empire waist Hem slightly uneven, faint makeup marks',
            ),
            16 => 
            array (
                'product_id' => 17,
                'name' => 'Tommy Hilfiger Denim Jacket',
                'price' => 331,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Tommy Hilfiger Denim Jacket.png',
                'product_condition' => 'gently used',
                'brand' => 'Tommy Hilfiger',
                'meterial' => 'denim',
                'color' => 'blue',
                'size_fit' => 'large, classic fit',
                'notes' => 'Tommy Hilfiger Denim Jacket-gently used Tommy Hilfiger denim blue large, classic fit Slight rust on ',
            ),
            17 => 
            array (
                'product_id' => 18,
                'name' => 'Puma Sports Tee',
                'price' => 676,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Puma Sports Tee.png',
                'product_condition' => 'lightly used',
                'brand' => 'Puma',
                'meterial' => 'polyester',
                'color' => 'red',
                'size_fit' => 'medium, regular fit',
                'notes' => 'Puma Sports Tee-lightly used Puma polyester red medium, regular fit Print faded from washing, fabric',
            ),
            18 => 
            array (
                'product_id' => 19,
                'name' => 'American Eagle Outfitters Shorts',
                'price' => 478,
                'category' => 'Clothes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'American Eagle Outfitters Shorts.png',
                'product_condition' => 'used',
                'brand' => 'American Eagle',
                'meterial' => 'cotton',
                'color' => 'khaki',
                'size_fit' => '32 waist, regular fit',
                'notes' => 'American Eagle Outfitters Shorts-used American Eagle cotton khaki 32 waist, regular fit Distressed e',
            ),
            19 => 
            array (
                'product_id' => 20,
                'name' => 'Burberry Trench Coat',
                'price' => 607,
                'category' => 'Clothes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Burberry Trench Coat.png',
                'product_condition' => 'vintage',
                'brand' => 'Burberry',
                'meterial' => 'cotton gabardine',
                'color' => 'beige',
                'size_fit' => 'medium, tailored fit',
                'notes' => 'Burberry Trench Coat-vintage Burberry cotton gabardine beige medium, tailored fit Slight water stain',
            ),
            20 => 
            array (
                'product_id' => 21,
                'name' => 'Adidas Running Shoes',
                'price' => 540,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Adidas Running Shoes.png',
                'product_condition' => 'well-worn',
                'brand' => 'Adidas',
                'meterial' => 'synthetic',
                'color' => 'black',
                'size_fit' => 'size 10, snug fit',
                'notes' => 'Adidas Running Shoes-well-worn Adidas synthetic black size 10, snug fit Sole slightly worn, insole s',
            ),
            21 => 
            array (
                'product_id' => 22,
                'name' => 'Nike Air Max',
                'price' => 433,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Nike Sweatpants.png',
                'product_condition' => 'moderately used',
                'brand' => 'Nike',
                'meterial' => 'mesh',
                'color' => 'grey',
                'size_fit' => 'size 9, cushioned sole',
                'notes' => 'Nike Air Max-moderately used Nike mesh grey size 9, cushioned sole Minor scuff on the toe box, laces',
            ),
            22 => 
            array (
                'product_id' => 23,
                'name' => 'Converse All-Stars',
                'price' => 787,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Converse All-Stars.png',
                'product_condition' => 'lightly used',
                'brand' => 'Converse',
                'meterial' => 'canvas',
                'color' => 'red',
                'size_fit' => 'size 8, standard fit',
                'notes' => 'Converse All-Stars-lightly used Converse canvas red size 8, standard fit Canvas faded, small tear ne',
            ),
            23 => 
            array (
                'product_id' => 24,
                'name' => 'Dr. Martens Boots',
                'price' => 521,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Dr. Martens Boots.png',
                'product_condition' => 'vintage',
                'brand' => 'Dr. Martens',
                'meterial' => 'leather',
                'color' => 'black',
                'size_fit' => 'size 7, tight fit',
                'notes' => 'Dr. Martens Boots-vintage Dr. Martens leather black size 7, tight fit Leather creased at ankles, sli',
            ),
            24 => 
            array (
                'product_id' => 25,
                'name' => 'Vans Skate Shoes',
                'price' => 569,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Vans Skate Shoes.png',
                'product_condition' => 'used',
                'brand' => 'Vans',
                'meterial' => 'canvas',
                'color' => 'checkered',
                'size_fit' => 'size 11, comfortable fit',
                'notes' => 'Vans Skate Shoes-used Vans canvas checkered size 11, comfortable fit Faded pattern, slight detachmen',
            ),
            25 => 
            array (
                'product_id' => 26,
                'name' => 'Birkenstock Sandals',
                'price' => 595,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Birkenstock Sandals.png',
                'product_condition' => 'well-worn',
                'brand' => 'Birkenstock',
                'meterial' => 'cork and leather',
                'color' => 'brown',
                'size_fit' => 'size 6, wide fit',
                'notes' => 'Birkenstock Sandals-well-worn Birkenstock cork and leather brown size 6, wide fit Footbed shows impr',
            ),
            26 => 
            array (
                'product_id' => 27,
                'name' => 'Steve Madden Heels',
                'price' => 170,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Steve Madden Heels.png',
                'product_condition' => 'lightly used',
                'brand' => 'Steve Madden',
                'meterial' => 'suede',
                'color' => 'black',
                'size_fit' => 'size 7, high heel',
                'notes' => 'Steve Madden Heels-lightly used Steve Madden suede black size 7, high heel Heel tips worn, slight sc',
            ),
            27 => 
            array (
                'product_id' => 28,
                'name' => 'Clarks Desert Boots',
                'price' => 456,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Clarks Desert Boots.png',
                'product_condition' => 'gently used',
                'brand' => 'Clarks',
                'meterial' => 'suede',
                'color' => 'brown',
                'size_fit' => 'size 9, classic fit',
                'notes' => 'Clarks Desert Boots-gently used Clarks suede brown size 9, classic fit Leather creased, soles show m',
            ),
            28 => 
            array (
                'product_id' => 29,
                'name' => 'Reebok Trainers',
                'price' => 945,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Reebok Trainers.png',
                'product_condition' => 'used',
                'brand' => 'Reebok',
                'meterial' => 'mesh',
                'color' => 'blue',
                'size_fit' => 'size 10, athletic fit',
                'notes' => 'Reebok Trainers-used Reebok mesh blue size 10, athletic fit Fabric slightly loose on one side, insol',
            ),
            29 => 
            array (
                'product_id' => 30,
                'name' => 'Jimmy Choo High Heels',
                'price' => 478,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Jimmy Choo High Heels.png',
                'product_condition' => 'barely used',
                'brand' => 'Jimmy Choo',
                'meterial' => 'leather',
                'color' => 'grey',
                'size_fit' => 'size 8, elegant fit',
                'notes' => 'Jimmy Choo High Heels-barely used Jimmy Choo leather grey size 8, elegant fit Minor scuffs on the he',
            ),
            30 => 
            array (
                'product_id' => 31,
                'name' => 'New Balance Sneakers',
                'price' => 696,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'New Balance Sneakers.png',
                'product_condition' => 'well-worn',
                'brand' => 'New Balance',
                'meterial' => 'suede and mesh',
                'color' => 'grey',
                'size_fit' => 'size 11, comfortable fit',
                'notes' => 'New Balance Sneakers-well-worn New Balance suede and mesh grey size 11, comfortable fit Slight disco',
            ),
            31 => 
            array (
                'product_id' => 32,
                'name' => 'Timberland Boots',
                'price' => 698,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Timberland Boots.png',
                'product_condition' => 'moderately used',
                'brand' => 'Timberland',
                'meterial' => 'leather',
                'color' => 'wheat',
                'size_fit' => 'size 12, rugged fit',
                'notes' => 'Timberland Boots-moderately used Timberland leather wheat size 12, rugged fit Leather slightly scuff',
            ),
            32 => 
            array (
                'product_id' => 33,
                'name' => 'Gucci Loafers',
                'price' => 886,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Gucci Loafers.png',
                'product_condition' => 'like new',
                'brand' => 'Gucci',
                'meterial' => 'leather',
                'color' => 'black',
                'size_fit' => 'size 8, luxury fit',
                'notes' => 'Gucci Loafers-like new Gucci leather black size 8, luxury fit Creases on the top, heel shows wear.',
            ),
            33 => 
            array (
                'product_id' => 34,
                'name' => 'Crocs Sandals',
                'price' => 828,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Crocs Sandals.png',
                'product_condition' => 'used',
                'brand' => 'Crocs',
                'meterial' => 'rubber',
                'color' => 'navy',
                'size_fit' => 'size 7, relaxed fit',
                'notes' => 'Crocs Sandals-used Crocs rubber navy size 7, relaxed fit Color faded from sunlight exposure, strap s',
            ),
            34 => 
            array (
                'product_id' => 35,
                'name' => 'Skechers Walking Shoes',
                'price' => 757,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Skechers Walking Shoes.png',
                'product_condition' => 'lightly used',
                'brand' => 'Skechers',
                'meterial' => 'mesh',
                'color' => 'black',
                'size_fit' => 'size 9, cushioned fit',
                'notes' => 'Skechers Walking Shoes-lightly used Skechers mesh black size 9, cushioned fit Insoles compressed, sl',
            ),
            35 => 
            array (
                'product_id' => 36,
                'name' => 'Puma Running Shoes',
                'price' => 404,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Puma Running Shoes.png',
                'product_condition' => 'gently used',
                'brand' => 'Puma',
                'meterial' => 'synthetic',
                'color' => 'white',
                'size_fit' => 'size 10, sporty fit',
                'notes' => 'Puma Running Shoes-gently used Puma synthetic white size 10, sporty fit Mesh slightly torn near the ',
            ),
            36 => 
            array (
                'product_id' => 37,
                'name' => 'Balenciaga Sneakers',
                'price' => 610,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Balenciaga Sneakers.png',
                'product_condition' => 'like new',
                'brand' => 'Balenciaga',
                'meterial' => 'leather',
                'color' => 'white',
                'size_fit' => 'size 11, oversized fit',
                'notes' => 'Balenciaga Sneakers-like new Balenciaga leather white size 11, oversized fit Leather creased at the ',
            ),
            37 => 
            array (
                'product_id' => 38,
                'name' => 'Yeezy Boost 350',
                'price' => 823,
                'category' => 'Shoes',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Yeezy Boost 350.png',
                'product_condition' => 'worn once',
                'brand' => 'Yeezy',
                'meterial' => 'knit',
                'color' => 'black',
                'size_fit' => 'size 9, snug fit',
                'notes' => 'Yeezy Boost 350-worn once Yeezy knit black size 9, snug fit Slight discoloration on the knit upper, ',
            ),
            38 => 
            array (
                'product_id' => 39,
                'name' => 'Under Armour Sports Shoes',
                'price' => 849,
                'category' => 'Shoes',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Under Armour Sports Shoes.png',
                'product_condition' => 'moderately used',
                'brand' => 'Under Armour',
                'meterial' => 'synthetic',
                'color' => 'red',
                'size_fit' => 'size 8, athletic fit',
                'notes' => 'Under Armour Sports Shoes-moderately used Under Armour synthetic red size 8, athletic fit Laces slig',
            ),
            39 => 
            array (
                'product_id' => 40,
                'name' => 'Salvatore Ferragamo Dress Shoes',
                'price' => 658,
                'category' => 'Shoes',
                'nego_status' => 'non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Salvatore Ferragamo Dress Shoes.png',
                'product_condition' => 'vintage',
                'brand' => 'Salvatore Ferragamo',
                'meterial' => 'leather',
                'color' => 'black',
                'size_fit' => 'size 10, elegant fit',
                'notes' => 'Salvatore Ferragamo Dress Shoes-vintage Salvatore Ferragamo leather black size 10, elegant fit Leath',
            ),
            40 => 
            array (
                'product_id' => 41,
                'name' => 'Michael Kors Handbag',
                'price' => 723,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Michael Kors Handbag.png',
                'product_condition' => 'like new',
                'brand' => 'Michael Kors',
                'meterial' => 'leather',
                'color' => 'tan',
                'size_fit' => 'medium-sized, spacious interior',
                'notes' => 'Michael Kors Handbag-like new Michael Kors leather tan medium-sized, spacious interior Minor scratch',
            ),
            41 => 
            array (
                'product_id' => 42,
                'name' => 'Coach Shoulder Bag',
                'price' => 473,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Coach Shoulder Bag.png',
                'product_condition' => 'barely used',
                'brand' => 'Coach',
                'meterial' => 'canvas and leather',
                'color' => 'brown',
                'size_fit' => 'small, compact design',
                'notes' => 'Leather slightly faded, strap shows signs of wear.',
            ),
            42 => 
            array (
                'product_id' => 43,
                'name' => 'Kate Spade Clutch',
                'price' => 211,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Kate Spade Clutch.png',
                'product_condition' => 'like new',
                'brand' => 'Kate Spade',
                'meterial' => 'satin',
                'color' => 'black',
                'size_fit' => 'one size, elegant look',
                'notes' => 'Kate Spade Clutch-like new Kate Spade satin black one size, elegant look Minor scratch on the clasp,',
            ),
            43 => 
            array (
                'product_id' => 44,
                'name' => 'Longchamp Tote Bag',
                'price' => 156,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Longchamp Tote Bag.png',
                'product_condition' => 'gently used',
                'brand' => 'Longchamp',
                'meterial' => 'nylon',
                'color' => 'pink',
                'size_fit' => 'large, foldable',
                'notes' => 'Longchamp Tote Bag-gently used Longchamp nylon pink large, foldable Corners worn, small ink stain on',
            ),
            44 => 
            array (
                'product_id' => 45,
                'name' => 'Prada Crossbody Bag',
                'price' => 538,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Prada Crossbody Bag.png',
                'product_condition' => 'like new',
                'brand' => 'Prada',
                'meterial' => 'Saffiano leather',
                'color' => 'red',
                'size_fit' => 'medium, adjustable strap',
                'notes' => 'Prada Crossbody Bag-like new Prada Saffiano leather red medium, adjustable strap Slight wear on the ',
            ),
            45 => 
            array (
                'product_id' => 46,
                'name' => 'Fossil Satchel',
                'price' => 389,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Fossil Satchel.png',
                'product_condition' => 'barely used',
                'brand' => 'Fossil',
                'meterial' => 'leather',
                'color' => 'grey',
                'size_fit' => 'medium, multiple pockets',
                'notes' => 'Fossil Satchel-barely used Fossil leather grey medium, multiple pockets Zipper sticks occasionally, ',
            ),
            46 => 
            array (
                'product_id' => 47,
                'name' => 'Louis Vuitton Speedy',
                'price' => 957,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Louis Vuitton Speedy.png',
                'product_condition' => 'vintage',
                'brand' => 'Louis Vuitton',
                'meterial' => 'canvas and leather',
                'color' => 'brown',
                'size_fit' => 'small, iconic design',
                'notes' => 'Louis Vuitton Speedy-vintage Louis Vuitton canvas and leather brown small, iconic design Handles dar',
            ),
            47 => 
            array (
                'product_id' => 48,
                'name' => 'Gucci Marmont',
                'price' => 118,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Gucci Marmont.png',
                'product_condition' => 'well-worn',
                'brand' => 'Gucci',
                'meterial' => 'leather',
                'color' => 'black',
                'size_fit' => 'medium, luxury style',
                'notes' => 'Gucci Marmont-well-worn Gucci leather black medium, luxury style Minor scratch on the front flap, ha',
            ),
            48 => 
            array (
                'product_id' => 49,
                'name' => 'Hermes Birkin',
                'price' => 714,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Hermes Birkin.png',
                'product_condition' => 'lightly used',
                'brand' => 'Hermes',
                'meterial' => 'leather',
                'color' => 'beige',
                'size_fit' => 'large, exclusive design',
                'notes' => 'Hermes Birkin-lightly used Hermes leather beige large, exclusive design Slight wear on the corners, ',
            ),
            49 => 
            array (
                'product_id' => 50,
                'name' => 'Chanel Flap Bag',
                'price' => 296,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Chanel Flap Bag.png',
                'product_condition' => 'vintage',
                'brand' => 'Chanel',
                'meterial' => 'leather',
                'color' => 'navy',
                'size_fit' => 'medium, classic style',
                'notes' => 'Chanel Flap Bag-vintage Chanel leather navy medium, classic style Chain strap shows wear, leather sl',
            ),
            50 => 
            array (
                'product_id' => 51,
                'name' => 'Marc Jacobs Backpack',
                'price' => 699,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Marc Jacobs Backpack.png',
                'product_condition' => 'used',
                'brand' => 'Marc Jacobs',
                'meterial' => 'nylon',
                'color' => 'black',
                'size_fit' => 'large, casual look',
                'notes' => 'Marc Jacobs Backpack-used Marc Jacobs nylon black large, casual look Zipper tab missing, fabric slig',
            ),
            51 => 
            array (
                'product_id' => 52,
                'name' => 'YSL Clutch',
                'price' => 873,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'YSL Clutch.png',
                'product_condition' => 'like new',
                'brand' => 'Yves Saint Laurent',
                'meterial' => 'leather',
                'color' => 'red',
                'size_fit' => 'medium, chic style',
                'notes' => 'YSL Clutch-like new Yves Saint Laurent leather red medium, chic style Minor marks on the leather, ma',
            ),
            52 => 
            array (
                'product_id' => 53,
                'name' => 'Givenchy Antigona',
                'price' => 917,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Givenchy Antigona.png',
                'product_condition' => 'gently used',
                'brand' => 'Givenchy',
                'meterial' => 'leather',
                'color' => 'grey',
                'size_fit' => 'medium, structured design',
                'notes' => 'Givenchy Antigona-gently used Givenchy leather grey medium, structured design Small stain inside, ha',
            ),
            53 => 
            array (
                'product_id' => 54,
                'name' => 'Alexander Wang Bucket Bag',
                'price' => 367,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Alexander Wang Bucket Bag.png',
                'product_condition' => 'barely used',
                'brand' => 'Alexander Wang',
                'meterial' => 'leather',
                'color' => 'black',
                'size_fit' => 'small, modern style',
                'notes' => 'Alexander Wang Bucket Bag-barely used Alexander Wang leather black small, modern style Leather creas',
            ),
            54 => 
            array (
                'product_id' => 55,
                'name' => 'Tory Burch Tote',
                'price' => 174,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Tory Burch Tote.png',
                'product_condition' => 'used',
                'brand' => 'Tory Burch',
                'meterial' => 'canvas',
                'color' => 'navy',
                'size_fit' => 'large, versatile design',
                'notes' => 'Tory Burch Tote-used Tory Burch canvas navy large, versatile design Straps slightly frayed, small ma',
            ),
            55 => 
            array (
                'product_id' => 56,
                'name' => 'Chloe Drew Bag',
                'price' => 854,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Chloe Drew Bag.png',
                'product_condition' => 'lightly used',
                'brand' => 'Chloe',
                'meterial' => 'leather',
                'color' => 'tan',
                'size_fit' => 'small, elegant look',
                'notes' => 'Chloe Drew Bag-lightly used Chloe leather tan small, elegant look Slight scratch on the front, clasp',
            ),
            56 => 
            array (
                'product_id' => 57,
                'name' => 'Burberry Crossbody',
                'price' => 558,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Burberry Crossbody.png',
                'product_condition' => 'vintage',
                'brand' => 'Burberry',
                'meterial' => 'check canvas',
                'color' => 'beige',
                'size_fit' => 'medium, classic design',
                'notes' => 'Burberry Crossbody-vintage Burberry check canvas beige medium, classic design Buckle slightly tarnis',
            ),
            57 => 
            array (
                'product_id' => 58,
                'name' => 'Valentino Shoulder Bag',
                'price' => 582,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Valentino Shoulder Bag.png',
                'product_condition' => 'like new',
                'brand' => 'Valentino',
                'meterial' => 'leather',
                'color' => 'black',
                'size_fit' => 'medium, rockstud details',
                'notes' => 'Valentino Shoulder Bag-like new Valentino leather black medium, rockstud details Studs slightly tarn',
            ),
            58 => 
            array (
                'product_id' => 59,
                'name' => 'Miu Miu Satchel',
                'price' => 280,
                'category' => 'Bags',
                'nego_status' => 'Negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Miu Miu Satchel.png',
                'product_condition' => 'gently used',
                'brand' => 'Miu Miu',
                'meterial' => 'leather',
                'color' => 'pink',
                'size_fit' => 'small, feminine style',
                'notes' => 'Miu Miu Satchel-gently used Miu Miu leather pink small, feminine style Minor wear on the handle, sma',
            ),
            59 => 
            array (
                'product_id' => 60,
                'name' => 'Dolce & Gabbana Clutch',
                'price' => 504,
                'category' => 'Bags',
                'nego_status' => 'Non-negotiable',
                'seller_id' => 0,
                'availability' => 'available',
                'product_photo' => 'Dolce & Gabbana Clutch.png',
                'product_condition' => 'barely used',
                'brand' => 'Dolce & Gabbana',
                'meterial' => 'leather',
                'color' => 'gold',
                'size_fit' => 'one size, glamorous look',
                'notes' => 'Dolce & Gabbana Clutch-barely used Dolce & Gabbana leather gold one size, glamorous look Fabric slig',
            ),
        ));
        
        
    }
}