<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'user_id' => 1,
                'first_name' => 'Daiben',
                'last_name' => 'Sanchez',
                'email_address' => 'daiben@gmail.com',
                'username' => 'daiben',
                'password' => '1234',
                'phone_number' => '09179303808',
                'address_street' => '123 Sampaguita St.',
                'address_barangay' => 'San Isidro',
                'address_citytown' => 'Quezon City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1100',
                'role' => 'seller',
                'profile_photo' => NULL,
            ),
            1 => 
            array (
                'user_id' => 2,
                'first_name' => 'Queza',
                'last_name' => 'Fabela',
                'email_address' => 'queza@gmail.com',
                'username' => 'queza',
                'password' => '1234',
                'phone_number' => '09174747713',
                'address_street' => '456 Kalayaan Ave.',
                'address_barangay' => 'Maginhawa',
                'address_citytown' => 'Makati City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1200',
                'role' => 'seller',
                'profile_photo' => NULL,
            ),
            2 => 
            array (
                'user_id' => 3,
                'first_name' => 'Dante',
                'last_name' => 'Magbuhos',
                'email_address' => 'dante@gmail.com',
                'username' => 'dante',
                'password' => '1234',
                'phone_number' => '09178343509',
                'address_street' => '789 Rizal Blvd.',
                'address_barangay' => 'Sta. Cruz',
                'address_citytown' => 'Manila',
                'address_province' => 'Metro Manila',
                'address_zip' => '1000',
                'role' => 'seller',
                'profile_photo' => NULL,
            ),
            3 => 
            array (
                'user_id' => 4,
                'first_name' => 'Paul',
                'last_name' => 'Quiachon',
                'email_address' => 'john@gmail.com',
                'username' => 'paul',
                'password' => '1234',
                'phone_number' => '09177331567',
                'address_street' => '1010 Mabini Lane',
                'address_barangay' => 'Bagumbayan',
                'address_citytown' => 'Taguig City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1630',
                'role' => 'seller',
                'profile_photo' => NULL,
            ),
            4 => 
            array (
                'user_id' => 5,
                'first_name' => 'Tanna',
                'last_name' => 'Slay',
                'email_address' => 'tanna@gmail.com',
                'username' => 'tanna',
                'password' => '1234',
                'phone_number' => '09170259742',
                'address_street' => '1112 Bonifacio Drive',
                'address_barangay' => 'Poblacion',
                'address_citytown' => 'Pasig City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1600',
                'role' => 'seller',
                'profile_photo' => NULL,
            ),
            5 => 
            array (
                'user_id' => 6,
                'first_name' => 'CJ',
                'last_name' => 'Salvino',
                'email_address' => 'cj@gmail.com',
                'username' => 'cj',
                'password' => '1234',
                'phone_number' => '09171350692',
                'address_street' => '1314 Malakas St',
                'address_barangay' => 'San Antonio',
                'address_citytown' => 'Parañaque City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1700',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
            6 => 
            array (
                'user_id' => 7,
                'first_name' => 'Kevin',
                'last_name' => 'Daus',
                'email_address' => 'kevin@gmail.com',
                'username' => 'kevin',
                'password' => '1234',
                'phone_number' => '09172255626',
                'address_street' => '1516 Maginhawa St.',
                'address_barangay' => 'Krus na Ligas',
                'address_citytown' => 'Quezon City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1101',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
            7 => 
            array (
                'user_id' => 8,
                'first_name' => 'Maynard',
                'last_name' => 'Villalobos',
                'email_address' => 'maynard@gmail.com',
                'username' => 'maynard',
                'password' => '1234',
                'phone_number' => '09175964817',
                'address_street' => '1718 Roxas Blvd.',
                'address_barangay' => 'Tambo',
                'address_citytown' => 'Pasay City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1300',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
            8 => 
            array (
                'user_id' => 9,
                'first_name' => 'April',
                'last_name' => 'Ipac',
                'email_address' => 'april@gmail.com',
                'username' => 'april',
                'password' => '1234',
                'phone_number' => '09176067490',
                'address_street' => '1920 Del Pilar Ave.',
                'address_barangay' => 'San Miguel',
                'address_citytown' => 'Manila',
                'address_province' => 'Metro Manila',
                'address_zip' => '1005',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
            9 => 
            array (
                'user_id' => 10,
                'first_name' => 'Jehd',
                'last_name' => 'Jandoc',
                'email_address' => 'jehd@gmail.com',
                'username' => 'jehd',
                'password' => '1234',
                'phone_number' => '09171412214',
                'address_street' => '2122 Aguinaldo St.',
                'address_barangay' => 'Palanan',
                'address_citytown' => 'Makati City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1235',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
            10 => 
            array (
                'user_id' => 11,
                'first_name' => 'Christian Jeuel',
                'last_name' => 'Venturina',
                'email_address' => 'christian@gmail.com',
                'username' => 'christian',
                'password' => '1234',
                'phone_number' => '09178327730',
                'address_street' => '2324 Balagtas St.',
                'address_barangay' => 'Santo Niño',
                'address_citytown' => 'Marikina City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1800',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
            11 => 
            array (
                'user_id' => 12,
                'first_name' => 'Jeinin',
                'last_name' => 'Arellano',
                'email_address' => 'jeinin@gmail.com',
                'username' => 'jeinin',
                'password' => '1234',
                'phone_number' => '09178548263',
                'address_street' => '2526 Lapu-Lapu Ave.',
                'address_barangay' => 'Maybunga',
                'address_citytown' => 'Pasig City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1607',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
            12 => 
            array (
                'user_id' => 13,
                'first_name' => 'Rafael',
                'last_name' => 'Uchi',
                'email_address' => 'rafael@gmail.com',
                'username' => 'rafael',
                'password' => '1234',
                'phone_number' => '09171792646',
                'address_street' => '2728 Katipunan Rd.',
                'address_barangay' => 'Loyola Heights',
                'address_citytown' => 'Quezon City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1108',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
            13 => 
            array (
                'user_id' => 14,
                'first_name' => 'Keith',
                'last_name' => 'Aquino',
                'email_address' => 'keith@gmail.com',
                'username' => 'keith',
                'password' => '1234',
                'phone_number' => '09178692271',
                'address_street' => '2930 Osmeña St.',
                'address_barangay' => 'San Lorenzo',
                'address_citytown' => 'Makati City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1223',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
            14 => 
            array (
                'user_id' => 15,
                'first_name' => 'Rendell',
                'last_name' => 'Soberano',
                'email_address' => 'rendell@gmail.com',
                'username' => 'rendell',
                'password' => '1234',
                'phone_number' => '09171981657',
                'address_street' => '3132 Magsaysay Blvd.',
                'address_barangay' => 'Santa Mesa',
                'address_citytown' => 'Manila',
                'address_province' => 'Metro Manila',
                'address_zip' => '1016',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
            15 => 
            array (
                'user_id' => 16,
                'first_name' => 'Angelica',
                'last_name' => 'Libang',
                'email_address' => 'angelica@gmail.com',
                'username' => 'angelica',
                'password' => '1234',
                'phone_number' => '09171513598',
                'address_street' => '3334 Luna St.',
                'address_barangay' => 'Ususan',
                'address_citytown' => 'Taguig City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1639',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
            16 => 
            array (
                'user_id' => 17,
                'first_name' => 'Vivien',
                'last_name' => 'Caampued',
                'email_address' => 'vivien@gmail.com',
                'username' => 'vivien',
                'password' => '1234',
                'phone_number' => '09178777201',
                'address_street' => '3536 Burgos Ave.',
                'address_barangay' => 'Almanza',
                'address_citytown' => 'Las Piñas City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1750',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
            17 => 
            array (
                'user_id' => 18,
                'first_name' => 'Fernando',
                'last_name' => 'Valenzuela',
                'email_address' => 'fernando@gmail.com',
                'username' => 'fernando',
                'password' => '1234',
                'phone_number' => '09171171463',
                'address_street' => '3738 Quezon Ave.',
                'address_barangay' => 'West Triangle',
                'address_citytown' => 'Quezon City',
                'address_province' => 'Metro Manila',
                'address_zip' => '1104',
                'role' => 'shopper',
                'profile_photo' => NULL,
            ),
        ));
        
        
    }
}